import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";
import Navbar from "./components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Brainstorm",
  description: "Generated by Brainstorm",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>

        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        {children}
        <Navbar />

      </body>
    </html>
  );
}
